---
name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: null
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: adopt
      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew
      - name: Run ktlint Format
        run: ./gradlew ktlintFormat
      - name: Run ktlint Check
        run: ./gradlew ktlintCheck
      - name: Run Detekt
        run: ./gradlew detekt
